name: Ruby
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
          - '3.2'
          - '3.3'
          - ruby-head
          - jruby-9.3.3.0
          - jruby-9.4
        include:
          - ruby: ruby-head
            env:
              RUBYOPT: '--jit'
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
        env:
          LONG_RUN: true

